In [3]:
# 1Q. Import numpy as np and print the version number.

import numpy as np

np.__version__

'1.17.4'

In [4]:
# 2Q. Create a 1D array of numbers from 0 to 9

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 3Q. Create a 3×3 numpy array of all True’s

np.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
# 4Q. Extract all odd numbers from arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2!=0]


array([1, 3, 5, 7, 9])

In [13]:
# 5Q. Replace all odd numbers in arr with -1

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr%2!=0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
# 6Q. Replace all odd numbers in arr with -1 without changing arr

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr2 = np.where(arr%2!=0, -1, arr)
print(arr2)
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [20]:
# 7Q. Convert a 1D array to a 2D array with 2 rows

arr = np.arange(10)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
# 8Q. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# 9Q. Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [30]:
# 10Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a

# Desired output
#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

a = np.array([1,2,3])

np.concatenate((np.repeat(a,3), np.tile(a,3)), axis=0)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
#  11Q. Get the common items between a and b

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [33]:
# 12Q. From array a remove all items present in array b

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [34]:
# 13Q. Get the positions where elements of a and b match

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)

In [46]:
#  14Q. Get all items between 5 and 10 from a

a = np.array([2, 6, 1, 9, 10, 3, 27])

a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [50]:
# 15Q. Convert the function maxx that works on two scalars, to work on two arrays.

# def maxx(x, y):
#     """Get the maximum of two items"""
#     if x >= y:
#         return x
#     else:
#         return y

# maxx(1, 5)

def maxx(x, y):
    return np.maximum(x,y)

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

maxx(a, b)



array([6, 7, 9, 8, 9, 7, 5])

In [54]:
# 16Q. Swap columns 1 and 2 in the array arr

arr = np.arange(9).reshape(3,3)
print(arr)
print()

arr[:,[0,1]] = arr[:,[1,0]]
print(arr)


[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [56]:
# 17Q. Swap rows 1 and 2 in the array arr

arr = np.arange(9).reshape(3,3)
print(arr)
print()

print(arr[[1,0,2],:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [58]:
# 18Q. Reverse the rows of a 2D array arr

arr = np.arange(9).reshape(3,3)
print(arr)
print()

print(arr[::-1,:])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [59]:
# 19Q. Reverse the columns of a 2D array arr

arr = np.arange(9).reshape(3,3)
print(arr)
print()

print(arr[:,::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [61]:
# 20Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

np.random.uniform(5,10,(5,3))

array([[8.95481288, 8.90259042, 6.6566036 ],
       [8.66230143, 8.75079954, 9.00661564],
       [7.06456739, 7.66991167, 6.21645449],
       [7.83417429, 8.82523069, 5.14103186],
       [5.57739592, 9.19947117, 8.41780664]])

In [62]:
# 21Q. Print or show only 3 decimal places of the numpy array rand_arr

rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr


array([[0.337, 0.818, 0.797],
       [0.396, 0.369, 0.161],
       [0.678, 0.318, 0.277],
       [0.991, 0.72 , 0.861],
       [0.052, 0.525, 0.527]])